### ISSUE TITLE
'R' followed by any capital letter with a serif gives just a (sligthtly smaller) 'R'

### ISSUE THREAD

**Issue by bilfri** [indestructible-type/Besley#10]
When I type eg. 'RH' only an 'R' shows. This is the same for all capital letters with serifs except Æ and Å. It's not critical, because typing the second letter again will make it show, but it's a sligthly jarring typing experience. Happens in both italic and regular and all weights as far as i can see.

**Comment by kenmcd** [comment]
I assume you mean accents/diacritics rather than serif.

This appears to be another Contextual Alternates issue.
The `RR` is getting replaced with `R.alt`, but only in the Regular fonts this time.

**Comment by EwonRael** [comment]
This is bad news. It is a contextual substitution issue. Can you do me a favor and see if something similar breaks when typing "ft" in the italics version? What software are you having this issue on?

**Comment by kenmcd** [comment]
The `RR` works in Bodoni.
And Bodoni Italic (or Reg) does not have the `ft` ligature anywhere.

**Comment by EwonRael** [comment]
This should be fixed. Terrible issue thanks for bringing this to my attention.
