### ISSUE TITLE
Not all weights available at https://indestructibletype.com/fonts/Besley.css

### ISSUE THREAD

**Issue by bilfri** [indestructible-type/Besley#13]
I'm using a wordpress plugin where you can only add one weight at a time, but I still wanted the auto-update advantages of the online repository. So I made a hacky solution and guessed the url of the specific weights from the content in the .css file. Any way, I noticed not all weights are there. I feel like this might be on purpose due to some restrictions of font support in css or whatever, but if it's not I just wanted to let you know.

**Comment by ctrlcctrlv** [comment]
Sorry, closing due to wrong repo, this is for the font not Owen's website.
