### ISSUE TITLE
Italics - Quotation Marks at the end of sentence are far away from Text

### ISSUE THREAD

**Issue by am-cmyk** [indestructible-type/Besley#26]
First to say: I love Besley. It has that classic appearance with a modern presentation. Thank you for your hard work!
I want to use it for a theatre branding and while checking i found an issue with the quotation marks in the italics (i made a screenshot). There is no space key after the last word.
Sorry for my bad english.

![seltsames_Anfuehrungszeichen](https://user-images.githubusercontent.com/52694377/193052637-44eea8a8-8ed4-4472-9011-d3e7dd4c17a1.png)

**Comment by EwonRael** [comment]
fixed. thanks for bringing to my attention
