### ISSUE TITLE
Rendering issue on 2 f's in a row

### ISSUE THREAD

**Issue by florik97** [indestructible-type/Besley#3]
See screenshot:

![screenshot 2019-02-20 at 11 03 03](https://user-images.githubusercontent.com/30573357/53083548-71ad5300-34ff-11e9-9e22-fd9f731b7cda.png)

kind regards,
Flo

**Comment by EwonRael** [comment]
That's called a ligature and it's intentional.Thanks!OwenOn Feb 20, 2019 02:06, florik97 <notifications@github.com> wrote:See screenshot:

kind regards,
Flo
