### ISSUE TITLE
Romanian glyhps

### ISSUE THREAD

**Issue by liviuvasilescu** [indestructible-type/Besley#4]
Please add “ă/Ă” and fix ”î“ — ”î” should have just the circumflex.

<img width="816" alt="screenshot 2019-03-07 at 17 21 24" src="https://user-images.githubusercontent.com/48325536/53967206-72e49f80-40fd-11e9-9b49-7ad0b3888740.png">

**Comment by EwonRael** [comment]
Besley* now has proper Romanian support
