### ISSUE TITLE
í has accent on top of tittle

### ISSUE THREAD

**Issue by thiagovscoelho** [indestructible-type/Besley#5]
Similar to issue #4 with the circumflex.

![image](https://user-images.githubusercontent.com/47187428/58747943-5def8200-8448-11e9-943e-c6f495b0501a.png)

**Comment by EwonRael** [comment]
yes this is a problem. I have honestly been avoiding updating Besley* for a while and it deserves some major fixes. This will undoubtedly be in the next update.

**Comment by ousia** [comment]
@EwonRael, this font is amazing, but its major issue is that all _i + diacritics_ glyphs should use the dotless  i glyph to be combined with diacritcs.

**Comment by freiredafonseca** [comment]
@EwonRael any news regarding the next update? This font is amazing and I would really like to use it on an upcoming project

**Comment by luuurq** [comment]
Hi @EwonRael ! First of all, thank you for sharing!! <3 I'm dropping by to report the same issue. I will use the font in a logo that uses the "í", so for now, I just manually fixed it in Illustrator :) It would be great to be able to use the font in larger pieces of texts without concerns about this character ;) thanks!

**Comment by EwonRael** [comment]
I'm currently working on updating Besley* 
If work keeps up at this pace I should have the romans finished by this time next week.
The italics will take longer but if it's any help I'm thinking of sharing the updated romans as soon as they're finished.

**Comment by EwonRael** [comment]
Latest version has all this fixed!
