### ISSUE TITLE
way too much space after "ø"-character.

### ISSUE THREAD

**Issue by bilfri** [indestructible-type/Besley#7]
Hi Owen,
Love your work. The Besley* makes a lot of space after the "ø"-character, which makes it unusable for danish. It's only for the lower case character. I'm very sad about this since I would really like to use it on my website. Other danish letters, æ and å, work okay, but I'd say the space after the æ is a little tight especially in italic. If it helps for bug fixing I'm running Linux Mint 20. I'm experiencing this error for all weights and in all my graphics software.
Have a good one,
Lukas

**Comment by EwonRael** [comment]
Hi.

The Besley* I am currently working on. It has many issues. I am already done fixing the roman version and hope to finish the italic soon. This will address the issue. I'll write when it's done.

**Comment by EwonRael** [comment]
This is now fixed!
