### ISSUE TITLE
Adding №(U+2116)

### ISSUE THREAD

**Issue by ezgranet** [indestructible-type/Besley#8]
Would it be possible to please add a glyph for the Numero sign (U+2116 / №)?  In my (very very amateur mockup), the existing glyphs for N and O, along with an underline and a bit of superscript, look quite nice!  Thank you very much for this wonderful typeface!

![Screenshot 2021-01-05 at 2 53 23 pm](https://user-images.githubusercontent.com/7822086/103654162-cf1ce280-4f65-11eb-889a-0f9a855f27d9.png)

**Comment by EwonRael** [comment]
added
