### ISSUE TITLE
the 'ft' combination in italic gives just a 't'

### ISSUE THREAD

**Issue by bilfri** [indestructible-type/Besley#9]
It happens for me in all weights except fatface. With the version downloaded from the homepage 2020-01-05.

**Comment by kenmcd** [comment]
There is an error in the Contextual Alternates (`calt`) code.

This:
```
feature ContextualAlternates calt {
  lookup ChainingContext1;
}
```
Calls this:
```
lookup ChainingContext1 {
  subtable "Subtable 1" {
    context @CG__R @CG__A;
    sub 0 Ligature1;
  }
  subtable "Subtable 2" {
    context @CG__f @CG__t;
    sub 0 Ligature2;
  }
}
```
Which calls this:
```
lookup Ligature2 {
  sub f t -> t.alt;
}
```
And that replaces the `ft` with the alternate `t`.

**Comment by EwonRael** [comment]
This should be fixed! Thanks for bringing up.
